# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
automation ow_automation: !include Modell_Haus_Automation.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

pyscript:
  allow_all_imports: true
  hass_is_global: true
  requirements:
    - pandas==1.5.3
    
    
python_script:
  requirements: # hier müssen die libraries ergänzt werden
  - paramiko>=2.7.1
  - pandas>0 1.1.1
  
    
    
    
logger:
  default: info
  logs:
    custom_components.pysrcipt: debug

influxdb:
  api_version: 2
  ssl: false
  host: xplore-dna.de
  port: 8086
  token: 9K-wDPPY7_JbiJP2I94UAMdmKH5ewNCIv_W2xkIni9UILjlaA32diHdkBoPdMTE6S4kVmlec0olgn7nGr3N8KA==
  organization: 5d09656bc55017d7
  bucket: heizungssteuerung
  default_measurement: state
  
  
input_number:
  heating_temperature:
    name: Heiztemperatur
    initial: 13
    min: 10
    max: 30
    step: 0.5

browser_mod:


