
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes



http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 100.104.187.13  #TailscaleIP des Strato Servers





automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

group: !include group.yaml

input_number: !include helpers_input_number.yaml
input_select: !include helpers_input_select.yaml
template: !include helpers_sensor.yaml
input_boolean: !include helpers_input_boolean.yaml




    
    
logger:
  default: info
  logs:
    custom_components.pysrcipt: debug

influxdb:
  api_version: 2
  ssl: false
  host: xplore-dna.de
  port: 8086
  token: 9K-wDPPY7_JbiJP2I94UAMdmKH5ewNCIv_W2xkIni9UILjlaA32diHdkBoPdMTE6S4kVmlec0olgn7nGr3N8KA==
  organization: 5d09656bc55017d7
  bucket: heizungssteuerung
  default_measurement: state